"""Handler for init command."""

from __future__ import annotations

import argparse
from pathlib import Path

from github_agent_orchestrator.orchestrator.cli_env import upsert_env_vars
from github_agent_orchestrator.orchestrator.config import OrchestratorSettings

_INIT_HEADER = (
    "# GitHub Agent Orchestrator",
    "# Generated by `orchestrator init`",
)


def handle_init(args: argparse.Namespace, settings: OrchestratorSettings) -> int:  # noqa: ARG001
    """Handle the init command."""

    env_path = Path(args.env_path).expanduser()

    updates: dict[str, str] = {}
    if args.repo:
        updates["ORCHESTRATOR_DEFAULT_REPO"] = args.repo
    if args.loop_mode:
        updates["ORCHESTRATOR_LOOP_MODE"] = args.loop_mode
    updates.setdefault("ORCHESTRATOR_CREATE_WORK_BRANCH", "true")

    upsert_env_vars(
        path=env_path,
        updates=updates,
        overwrite=args.force,
        header=_INIT_HEADER,
    )

    print(f"Initialized {env_path}")
    if updates:
        print("Configured:")
        for key, value in updates.items():
            print(f"- {key}={value}")
    print("Next steps:")
    print("- orchestrator auth github --token <YOUR_TOKEN>")
    print("- orchestrator run --repo <owner/repo>")
    return 0
